version: '3.1'

services:

  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9040:8082
    environment:
      VIRTUAL_HOST: ocr.scrap.devent.kr
      LETSENCRYPT_HOST: ocr.scrap.devent.kr
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"

